//
// Created by 程宇栋 on 2024/9/19.
//

#ifndef EXPO_PANORAMA_VIEW_EXAMPLE_SIZEMODE_H
#define EXPO_PANORAMA_VIEW_EXAMPLE_SIZEMODE_H

enum SizeMode {
    FIT,
    SCALE_FULL,
};

#endif //EXPO_PANORAMA_VIEW_EXAMPLE_SIZEMODE_H
